# Generated by Django 3.1.5 on 2022-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechapimodel',
            name='date',
        ),
        migrations.AddField(
            model_name='speechapimodel',
            name='result',
            field=models.TextField(blank=True),
        ),
    ]
